inherit: ["config.yml"]

# 電子版を別のファイル名にしたい場合:
bookname: ebook

# B5(10pt 40文字×35行)設定例:
texdocumentclass: ["review-jlreq", "media=ebook,paper=b5j,openany,fontsize=10pt,line_length=40zw,number_of_lines=35"]
# A5(9pt 38文字×37行)設定例:
# texdocumentclass: ["review-jlreq", "media=ebook,paper=a5,fontsize=9pt,line_length=38zw,number_of_lines=37"]
