name: Build Re:VIEW to make distribution file
# The workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v3
    # Build Artifacts
    - uses: addnab/docker-run-action@v3
      with:
        image: vvakame/review:5.5
        options: -v ${{ github.workspace }}:/work
        run: |
          cd /work && \
          bundle install && \
          rake pdf:grayscale
    - name: Upload distribution files to GitHub artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Output documents (PDF)
        path: ./articles/*.pdf
